const express=require("express")
const cookieParser = require('cookie-parser')
const app=express()
require('dotenv').config()
const databaseconnection=require("./database/databaseconfic")
const productrouter=require("./routers/productsrouter")
const auth=require("./routers/authrouter")
const order=require("./routers/orderrouter")
var cors = require('cors')
databaseconnection()
app.use(express.urlencoded({extended:true}))
app.use(express.json())
app.use(cors())
app.use(cookieParser());
app.use('/api',productrouter)
app.use('/api',auth)
app.use('/api',order)
const PORT=process.env.PORT
app.listen(PORT,()=>console.log(`http://localhost:${PORT}`))
